---
- name: Reload systemd
  systemd:
    daemon_reload: true
  notify: Restart opensmtpd

- name: Restart opensmtpd
  service:
    name: "{{ smtpd_service }}"
    state: restarted

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
